"""changing primary key id

Revision ID: 69812958030e
Revises: 9aa0046ebc90
Create Date: 2019-09-03 09:09:54.680635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69812958030e'
down_revision = '9aa0046ebc90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guild',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('prefix', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guild.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    op.drop_table('guild')
    # ### end Alembic commands ###
