"""adding empty_count for Category table

Revision ID: 760c60b33f07
Revises: 69812958030e
Create Date: 2019-09-03 11:40:37.570688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '760c60b33f07'
down_revision = '69812958030e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('empty_count', sa.Integer(), nullable=True))
    empty = sa.table('category', sa.Column('empty_count'))
    op.execute(empty.update().values(empty_count=1))
    op.alter_column('category', 'empty_count', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'empty_count')
    # ### end Alembic commands ###
