"""createing columns for custom voice commands

Revision ID: ad39e8c33891
Revises: 11b55cea52bb
Create Date: 2019-09-11 14:41:07.101841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad39e8c33891'
down_revision = '11b55cea52bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('custom_enabled', sa.Boolean(), nullable=True))
    op.add_column('category', sa.Column('custom_prefix', sa.String(length=10), nullable=True))
    c_enabled = sa.table('category', sa.Column('custom_enabled'))
    op.execute(c_enabled.update().values(custom_enabled=False))
    c_prefix = sa.table('category', sa.Column('custom_prefix'))
    op.execute(c_prefix.update().values(custom_prefix="VC!"))
    op.alter_column('category', 'custom_enabled', nullable=False)
    op.alter_column('category', 'custom_prefix', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'custom_prefix')
    op.drop_column('category', 'custom_enabled')
    # ### end Alembic commands ###
