"""empty message

Revision ID: c004761ac578
Revises: 760c60b33f07
Create Date: 2019-09-06 08:30:07.698256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c004761ac578'
down_revision = '760c60b33f07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('channel_size', sa.Integer(), nullable=True))
    c_size = sa.table('category', sa.Column('channel_size'))
    op.execute(c_size.update().values(channel_size=10))
    op.alter_column('category', 'channel_size', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'channel_size')
    # ### end Alembic commands ###
