"""changing table name

Revision ID: cd4835a51fcb
Revises: 5e7904e33be8
Create Date: 2019-10-10 17:57:15.425809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd4835a51fcb'
down_revision = '5e7904e33be8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cat_id', sa.BigInteger(), nullable=False),
    sa.Column('chan_type', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['cat_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('channels')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('cat_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('chan_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cat_id'], ['category.id'], name='channels_cat_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='channels_pkey')
    )
    op.drop_table('channel')
    # ### end Alembic commands ###
